SET NOCOUNT ON;
PRINT 'PROCESSING TIME ARTICLE EXAMPLES';
SELECT TOP (12) Artikelnummer,Beschreibung,BearbeitungszeitMin FROM dbo.ArtikelnummerZeit ORDER BY Artikelnummer;
PRINT 'SERVICE ARTICLE EXAMPLES';
SELECT TOP (15) ARTIKELNUMMER,KATALOGNUMMER,COUNT_BIG(*) AS services FROM dbo.DIENSTLEISTUNGEN GROUP BY ARTIKELNUMMER,KATALOGNUMMER ORDER BY services DESC;
PRINT 'CATALOG MATCH';
WITH times AS (SELECT Artikelnummer,MAX(BearbeitungszeitMin) AS minutes FROM dbo.ArtikelnummerZeit GROUP BY Artikelnummer)
SELECT COUNT_BIG(*) AS services,SUM(CASE WHEN t.minutes>0 THEN 1 ELSE 0 END) AS positive_time_via_catalog FROM dbo.DIENSTLEISTUNGEN d LEFT JOIN times t ON d.KATALOGNUMMER=t.Artikelnummer;
PRINT 'ASSESSMENT COUNTS';
SELECT LETZTE_BEWERTUNG,COUNT_BIG(*) AS instruments FROM dbo.MESSMITTEL GROUP BY LETZTE_BEWERTUNG ORDER BY instruments DESC;
PRINT 'DUE DATE YEAR COUNTS';
SELECT YEAR(DATUM_NAECHSTE_PRUEFUNG) AS yr,COUNT_BIG(*) AS instruments FROM dbo.MESSMITTEL GROUP BY YEAR(DATUM_NAECHSTE_PRUEFUNG) ORDER BY yr;
PRINT 'CUSTOMER HISTORY DEPTH';
WITH activity AS (SELECT KUNDENNUMMER_SAP,COUNT_BIG(*) AS n,COUNT(DISTINCT YEAR(BEGINN)*100+MONTH(BEGINN)) AS active_months FROM dbo.KALIBRIERUNGEN WHERE NULLIF(LTRIM(RTRIM(KUNDENNUMMER_SAP)),'') IS NOT NULL GROUP BY KUNDENNUMMER_SAP)
SELECT COUNT_BIG(*) AS customers_with_history,SUM(CASE WHEN active_months>=2 THEN 1 ELSE 0 END) AS customers_multiple_months,SUM(CASE WHEN active_months>=6 THEN 1 ELSE 0 END) AS customers_six_months,SUM(CASE WHEN n>=10 THEN 1 ELSE 0 END) AS customers_ten_calibrations FROM activity;
PRINT 'INDUSTRY IN CALIBRATION COHORT';
WITH history AS (SELECT DISTINCT KUNDENNUMMER_SAP FROM dbo.KALIBRIERUNGEN)
SELECT COUNT(*) AS customers,SUM(CASE WHEN b.KundenNr IS NOT NULL THEN 1 ELSE 0 END) AS with_industry,SUM(CASE WHEN b.Branche='Sonstiges' THEN 1 ELSE 0 END) AS other_industry FROM history h LEFT JOIN dbo.Kunde_Branche b ON h.KUNDENNUMMER_SAP=b.KundenNr;
PRINT 'LAB CAPACITY GRAIN';
SELECT 'actual' AS dataset,COUNT_BIG(*) AS rows,COUNT(DISTINCT CONCAT(CONVERT(varchar(10),Kalendertag,23),'|',KST,'|',MESSRAUM)) AS distinct_date_kst_lab, SUM(CASE WHEN [IST Anwesend STD] IS NULL THEN 1 ELSE 0 END) AS null_attendance,SUM(CASE WHEN [IST Anwesend STD]<0 THEN 1 ELSE 0 END) AS negative_attendance FROM dbo.[Ist_Stunden_24-26]
UNION ALL SELECT 'planned',COUNT_BIG(*),COUNT(DISTINCT CONCAT(CONVERT(varchar(10),[Kalendertag (Intervall)],23),'|',KST,'|',MESSRAUM)),SUM(CASE WHEN [SOLL Anwesend STD] IS NULL THEN 1 ELSE 0 END),SUM(CASE WHEN [SOLL Anwesend STD]<0 THEN 1 ELSE 0 END) FROM dbo.[Soll-Kapa];
PRINT 'INSTRUMENT TO HISTORY MATCH';
WITH history AS (SELECT DISTINCT MESSMITTEL_UUID FROM dbo.KALIBRIERUNGEN)
SELECT COUNT_BIG(*) AS instruments_with_history,SUM(CASE WHEN m.MESSMITTEL_UUID IS NOT NULL THEN 1 ELSE 0 END) AS matched_current_instrument FROM history h LEFT JOIN dbo.MESSMITTEL m ON h.MESSMITTEL_UUID=m.MESSMITTEL_UUID;
