SET NOCOUNT ON;

PRINT 'DATE COVERAGE';
SELECT 'calibrations' AS dataset, COUNT_BIG(*) AS rows, MIN(BEGINN) AS first_date, MAX(BEGINN) AS last_date FROM dbo.KALIBRIERUNGEN
UNION ALL SELECT 'order_positions',COUNT_BIG(*),MIN(dateErfasst),MAX(dateErfasst) FROM dbo.AUFTRAGSPOSITIONEN
UNION ALL SELECT 'services',COUNT_BIG(*),MIN(HINZUGEFUEGT_AM),MAX(HINZUGEFUEGT_AM) FROM dbo.DIENSTLEISTUNGEN
UNION ALL SELECT 'actual_hours',COUNT_BIG(*),MIN(Kalendertag),MAX(Kalendertag) FROM dbo.[Ist_Stunden_24-26]
UNION ALL SELECT 'planned_hours',COUNT_BIG(*),MIN([Kalendertag (Intervall)]),MAX([Kalendertag (Intervall)]) FROM dbo.[Soll-Kapa];

PRINT 'CALIBRATION HISTORY BY YEAR';
SELECT YEAR(BEGINN) AS yr,COUNT_BIG(*) AS calibrations,COUNT(DISTINCT MESSMITTEL_UUID) AS instruments,COUNT(DISTINCT KUNDENNUMMER_SAP) AS customers FROM dbo.KALIBRIERUNGEN GROUP BY YEAR(BEGINN) ORDER BY yr;

PRINT 'INSTRUMENT COMPLETENESS';
SELECT COUNT_BIG(*) AS instruments,COUNT(DISTINCT MESSMITTEL_UUID) AS unique_ids,
SUM(CASE WHEN DATUM_NAECHSTE_PRUEFUNG IS NULL THEN 1 ELSE 0 END) AS missing_due_date,
SUM(CASE WHEN PRUEFINTERVALL IS NULL OR PRUEFINTERVALL<=0 THEN 1 ELSE 0 END) AS missing_positive_interval,
SUM(CASE WHEN NULLIF(LTRIM(RTRIM(MESSRAUM)),'') IS NULL THEN 1 ELSE 0 END) AS missing_lab,
SUM(CASE WHEN NULLIF(LTRIM(RTRIM(KUNDENNUMMER_SAP)),'') IS NULL THEN 1 ELSE 0 END) AS missing_customer,
SUM(CASE WHEN FAELLIGKEIT_STOP=1 THEN 1 ELSE 0 END) AS due_stopped,
MIN(DATUM_NAECHSTE_PRUEFUNG) AS earliest_due, MAX(DATUM_NAECHSTE_PRUEFUNG) AS latest_due FROM dbo.MESSMITTEL;

PRINT 'DUE TYPE';
SELECT FAELLIGKEIT_TYP,COUNT_BIG(*) AS instruments,SUM(CASE WHEN DATUM_NAECHSTE_PRUEFUNG IS NULL THEN 1 ELSE 0 END) AS missing_due FROM dbo.MESSMITTEL GROUP BY FAELLIGKEIT_TYP ORDER BY instruments DESC;
PRINT 'INTERVAL UNITS';
SELECT EINHEIT_PRUEFINTERVALL,COUNT_BIG(*) AS instruments,MIN(PRUEFINTERVALL) AS min_interval,MAX(PRUEFINTERVALL) AS max_interval FROM dbo.MESSMITTEL GROUP BY EINHEIT_PRUEFINTERVALL ORDER BY instruments DESC;

PRINT 'PROCESSING TIMES';
SELECT COUNT_BIG(*) AS rows,COUNT(DISTINCT Artikelnummer) AS unique_articles, SUM(CASE WHEN BearbeitungszeitMin IS NULL OR BearbeitungszeitMin<=0 THEN 1 ELSE 0 END) AS missing_positive_time,MIN(BearbeitungszeitMin) AS min_minutes,MAX(BearbeitungszeitMin) AS max_minutes FROM dbo.ArtikelnummerZeit;
WITH times AS (SELECT Artikelnummer, MAX(BearbeitungszeitMin) AS minutes FROM dbo.ArtikelnummerZeit GROUP BY Artikelnummer)
SELECT COUNT_BIG(*) AS services, SUM(CASE WHEN t.Artikelnummer IS NOT NULL THEN 1 ELSE 0 END) AS article_matched,SUM(CASE WHEN t.minutes>0 THEN 1 ELSE 0 END) AS positive_time_matched,SUM(CASE WHEN NULLIF(LTRIM(RTRIM(d.ARTIKELNUMMER)),'') IS NULL THEN 1 ELSE 0 END) AS missing_article FROM dbo.DIENSTLEISTUNGEN d LEFT JOIN times t ON d.ARTIKELNUMMER=t.Artikelnummer;
PRINT 'SERVICE TIME MATCH BY TYPE';
WITH times AS (SELECT Artikelnummer, MAX(BearbeitungszeitMin) AS minutes FROM dbo.ArtikelnummerZeit GROUP BY Artikelnummer)
SELECT d.DIENSTLEISTUNGSTYP,COUNT_BIG(*) AS services,SUM(CASE WHEN t.minutes>0 THEN 1 ELSE 0 END) AS positive_time_matched FROM dbo.DIENSTLEISTUNGEN d LEFT JOIN times t ON d.ARTIKELNUMMER=t.Artikelnummer GROUP BY d.DIENSTLEISTUNGSTYP ORDER BY services DESC;

PRINT 'LABS AND CAPACITY MATCH';
WITH cal AS (SELECT LTRIM(RTRIM(MESSRAUM)) AS lab,COUNT_BIG(*) AS calibrations FROM dbo.KALIBRIERUNGEN GROUP BY LTRIM(RTRIM(MESSRAUM))),
actual AS (SELECT LTRIM(RTRIM(MESSRAUM)) AS lab,COUNT_BIG(*) AS actual_rows,SUM([IST Anwesend STD]) AS present_hours FROM dbo.[Ist_Stunden_24-26] GROUP BY LTRIM(RTRIM(MESSRAUM))),
planhrs AS (SELECT LTRIM(RTRIM(MESSRAUM)) AS lab,COUNT_BIG(*) AS planned_rows,SUM([SOLL Anwesend STD]) AS planned_present_hours FROM dbo.[Soll-Kapa] GROUP BY LTRIM(RTRIM(MESSRAUM)))
SELECT c.lab,c.calibrations,a.actual_rows,a.present_hours,p.planned_rows,p.planned_present_hours FROM cal c LEFT JOIN actual a ON c.lab=a.lab LEFT JOIN planhrs p ON c.lab=p.lab ORDER BY c.calibrations DESC;

PRINT 'MONTHLY HOURS';
SELECT 'actual' AS dataset,YEAR(Kalendertag) AS yr,MONTH(Kalendertag) AS mo,COUNT(*) AS rows, SUM([IST Anwesend STD]) AS attendance_hours,SUM([IST Krank STD]) AS sick_hours,SUM([IST Urlaub STD]) AS vacation_hours FROM dbo.[Ist_Stunden_24-26] GROUP BY YEAR(Kalendertag),MONTH(Kalendertag)
UNION ALL SELECT 'plan',YEAR([Kalendertag (Intervall)]),MONTH([Kalendertag (Intervall)]),COUNT(*),SUM([SOLL Anwesend STD]),SUM([SOLL Krank STD]),SUM([SOLL Urlaub STD]) FROM dbo.[Soll-Kapa] GROUP BY YEAR([Kalendertag (Intervall)]),MONTH([Kalendertag (Intervall)]) ORDER BY dataset,yr,mo;

PRINT 'CUSTOMER INDUSTRY';
SELECT Branche,COUNT_BIG(*) AS customers FROM dbo.Kunde_Branche GROUP BY Branche ORDER BY customers DESC;
WITH industries AS (SELECT DISTINCT KundenNr FROM dbo.Kunde_Branche)
SELECT COUNT_BIG(*) AS instruments,COUNT(DISTINCT m.KUNDENNUMMER_SAP) AS customers,SUM(CASE WHEN b.KundenNr IS NOT NULL THEN 1 ELSE 0 END) AS instruments_with_industry,COUNT(DISTINCT CASE WHEN b.KundenNr IS NOT NULL THEN m.KUNDENNUMMER_SAP END) AS customers_with_industry FROM dbo.MESSMITTEL m LEFT JOIN industries b ON m.KUNDENNUMMER_SAP=b.KundenNr;
PRINT 'REPEAT HISTORY';
WITH history AS (SELECT MESSMITTEL_UUID,COUNT_BIG(*) AS n FROM dbo.KALIBRIERUNGEN WHERE MESSMITTEL_UUID IS NOT NULL GROUP BY MESSMITTEL_UUID)
SELECT COUNT_BIG(*) AS instruments_with_history,SUM(CASE WHEN n>=2 THEN 1 ELSE 0 END) AS with_two_or_more,SUM(CASE WHEN n>=3 THEN 1 ELSE 0 END) AS with_three_or_more FROM history;

PRINT 'KEY UNIQUENESS';
SELECT 'order_positions' AS dataset,COUNT_BIG(*) AS rows,COUNT(DISTINCT UUID) AS unique_ids FROM dbo.AUFTRAGSPOSITIONEN
UNION ALL SELECT 'industry_customers',COUNT_BIG(*),COUNT(DISTINCT KundenNr) FROM dbo.Kunde_Branche;
PRINT 'SERVICE JOIN COVERAGE';
WITH orders AS (SELECT DISTINCT UUID FROM dbo.AUFTRAGSPOSITIONEN), instruments AS (SELECT DISTINCT MESSMITTEL_UUID FROM dbo.MESSMITTEL)
SELECT COUNT_BIG(*) AS services,SUM(CASE WHEN o.UUID IS NOT NULL THEN 1 ELSE 0 END) AS matched_order,SUM(CASE WHEN m.MESSMITTEL_UUID IS NOT NULL THEN 1 ELSE 0 END) AS matched_instrument FROM dbo.DIENSTLEISTUNGEN d LEFT JOIN orders o ON d.AUFTRAGSPOSITION_UUID=o.UUID LEFT JOIN instruments m ON d.UUID_KALIBRIERGEGENSTAND=m.MESSMITTEL_UUID;
PRINT 'ORDER STATUS';
SELECT statusPosition,COUNT_BIG(*) AS rows FROM dbo.AUFTRAGSPOSITIONEN GROUP BY statusPosition ORDER BY rows DESC;
