SET NOCOUNT ON;
PRINT 'CATALOG PROCESSING-TIME COVERAGE BY SERVICE TYPE';
WITH times AS (SELECT Artikelnummer,MAX(BearbeitungszeitMin) AS minutes FROM dbo.ArtikelnummerZeit GROUP BY Artikelnummer)
SELECT d.DIENSTLEISTUNGSTYP,COUNT_BIG(*) AS services,SUM(CASE WHEN t.minutes>0 THEN 1 ELSE 0 END) AS positive_time_matched FROM dbo.DIENSTLEISTUNGEN d LEFT JOIN times t ON d.KATALOGNUMMER=t.Artikelnummer GROUP BY d.DIENSTLEISTUNGSTYP ORDER BY services DESC;
PRINT 'MISSING DUE DATES WITH REPEAT HISTORY';
WITH history AS (SELECT MESSMITTEL_UUID,COUNT_BIG(*) AS n FROM dbo.KALIBRIERUNGEN GROUP BY MESSMITTEL_UUID)
SELECT COUNT_BIG(*) AS missing_due,SUM(CASE WHEN h.n>=2 THEN 1 ELSE 0 END) AS missing_due_with_repeat_history,SUM(CASE WHEN m.PRUEFINTERVALL>0 THEN 1 ELSE 0 END) AS missing_due_with_positive_interval FROM dbo.MESSMITTEL m LEFT JOIN history h ON m.MESSMITTEL_UUID=h.MESSMITTEL_UUID WHERE m.DATUM_NAECHSTE_PRUEFUNG IS NULL;
PRINT 'RECENT CALIBRATION VOLUME';
SELECT YEAR(BEGINN) AS yr,MONTH(BEGINN) AS mo,COUNT_BIG(*) AS calibrations FROM dbo.KALIBRIERUNGEN WHERE BEGINN>='2025-01-01' GROUP BY YEAR(BEGINN),MONTH(BEGINN) ORDER BY yr,mo;
PRINT 'LAB DUE DATE COVERAGE';
SELECT MESSRAUM,COUNT_BIG(*) AS instruments,SUM(CASE WHEN DATUM_NAECHSTE_PRUEFUNG IS NULL THEN 1 ELSE 0 END) AS missing_due_date FROM dbo.MESSMITTEL GROUP BY MESSRAUM ORDER BY instruments DESC;
