SET NOCOUNT ON;
PRINT 'CUSTOMER_MONTH';
SELECT CONVERT(varchar(64),HASHBYTES('SHA2_256',KUNDENNUMMER_SAP),2) AS customer,
CONVERT(char(7),BEGINN,126) AS month,COUNT_BIG(*) AS calibrations,
COUNT(DISTINCT MESSMITTEL_UUID) AS instruments,COUNT(DISTINCT MESSMITTELGRUPPE) AS instrument_groups,
COUNT(DISTINCT MESSRAUM) AS labs FROM dbo.KALIBRIERUNGEN
WHERE BEGINN>='2024-01-01' AND NULLIF(LTRIM(RTRIM(KUNDENNUMMER_SAP)),'') IS NOT NULL
GROUP BY KUNDENNUMMER_SAP,CONVERT(char(7),BEGINN,126) ORDER BY customer,month;
PRINT 'LAB_WEEK';
SELECT MESSRAUM AS lab,CONVERT(char(10),DATEADD(day,-(DATEDIFF(day,'19000101',CAST(BEGINN AS date))%7),CAST(BEGINN AS date)),23) AS week,COUNT_BIG(*) AS calibrations
FROM dbo.KALIBRIERUNGEN WHERE BEGINN>='2024-01-01'
GROUP BY MESSRAUM,DATEADD(day,-(DATEDIFF(day,'19000101',CAST(BEGINN AS date))%7),CAST(BEGINN AS date)) ORDER BY lab,week;
PRINT 'INTERVAL_DISTRIBUTION';
WITH dates AS (SELECT DISTINCT MESSMITTEL_UUID,CAST(BEGINN AS date) AS calibration_date FROM dbo.KALIBRIERUNGEN WHERE MESSMITTEL_UUID IS NOT NULL),
gaps AS (SELECT DATEDIFF(day,LAG(calibration_date) OVER(PARTITION BY MESSMITTEL_UUID ORDER BY calibration_date),calibration_date) AS gap_days FROM dates)
SELECT COUNT_BIG(*) AS observed_gaps,SUM(CASE WHEN gap_days BETWEEN 1 AND 30 THEN 1 ELSE 0 END) AS days_1_30,
SUM(CASE WHEN gap_days BETWEEN 31 AND 180 THEN 1 ELSE 0 END) AS days_31_180,
SUM(CASE WHEN gap_days BETWEEN 181 AND 450 THEN 1 ELSE 0 END) AS days_181_450,
SUM(CASE WHEN gap_days>450 THEN 1 ELSE 0 END) AS days_over_450 FROM gaps WHERE gap_days IS NOT NULL;
PRINT 'DUPLICATE_CALIBRATION_INSTRUMENT_DAYS';
SELECT COUNT_BIG(*) AS repeated_instrument_days,SUM(n-1) AS excess_rows FROM (SELECT MESSMITTEL_UUID,CAST(BEGINN AS date) AS dt,COUNT_BIG(*) AS n FROM dbo.KALIBRIERUNGEN GROUP BY MESSMITTEL_UUID,CAST(BEGINN AS date) HAVING COUNT_BIG(*)>1) d;
