SET NOCOUNT ON;
PRINT 'LAB_MONTH';
SELECT MESSRAUM AS lab,CONVERT(char(7),BEGINN,126) AS month,COUNT_BIG(*) AS calibrations
FROM dbo.KALIBRIERUNGEN WHERE BEGINN>='2024-01-01' AND BEGINN<'2026-09-01'
GROUP BY MESSRAUM,CONVERT(char(7),BEGINN,126) ORDER BY lab,month;
PRINT 'CAPACITY_MONTH';
SELECT 'actual' AS source,MESSRAUM AS lab,CONVERT(char(7),Kalendertag,126) AS month,
SUM([IST Anwesend STD]) AS attendance,SUM([IST Krank STD]) AS sick,SUM([IST Urlaub STD]) AS vacation,
SUM([IST Sonstiges STD]) AS other_hours,SUM([IST-Stunden Gesamtergebnis  STD]) AS total_hours,
COUNT(*) AS rows,COUNT([IST Anwesend STD]) AS attendance_nonnull
FROM dbo.[Ist_Stunden_24-26] GROUP BY MESSRAUM,CONVERT(char(7),Kalendertag,126)
UNION ALL
SELECT 'plan',MESSRAUM,CONVERT(char(7),[Kalendertag (Intervall)],126),SUM([SOLL Anwesend STD]),SUM([SOLL Krank STD]),SUM([SOLL Urlaub STD]),SUM([SOLL Sonstiges STD]),SUM([Gesamtergebnis STD]),COUNT(*),COUNT([SOLL Anwesend STD])
FROM dbo.[Soll-Kapa] GROUP BY MESSRAUM,CONVERT(char(7),[Kalendertag (Intervall)],126) ORDER BY source,lab,month;
PRINT 'SERVICE_COMPLETION_DATE';
SELECT COUNT_BIG(*) AS services,COUNT(QUITTIERT_AM) AS with_completion,MIN(QUITTIERT_AM) AS earliest_completion,MAX(QUITTIERT_AM) AS latest_completion,SUM(CASE WHEN QUITTIERT_AM<HINZUGEFUEGT_AM THEN 1 ELSE 0 END) AS completion_before_added FROM dbo.DIENSTLEISTUNGEN;
PRINT 'CALIBRATION_ORDER_LAB_MAPPING';
WITH lookup AS (
SELECT MESSMITTEL_UUID,AUFTRAGSNUMMER,MIN(MESSRAUM) AS lab,COUNT(DISTINCT MESSRAUM) AS lab_count
FROM dbo.KALIBRIERUNGEN GROUP BY MESSMITTEL_UUID,AUFTRAGSNUMMER)
SELECT COUNT_BIG(*) AS services,SUM(CASE WHEN c.MESSMITTEL_UUID IS NOT NULL THEN 1 ELSE 0 END) AS matched,
SUM(CASE WHEN c.lab_count=1 THEN 1 ELSE 0 END) AS unambiguous_lab,
SUM(CASE WHEN c.lab_count>1 THEN 1 ELSE 0 END) AS multiple_labs
FROM dbo.DIENSTLEISTUNGEN d LEFT JOIN lookup c ON d.UUID_KALIBRIERGEGENSTAND=c.MESSMITTEL_UUID AND d.AUFTRAGSNUMMER_SAP=c.AUFTRAGSNUMMER;
PRINT 'WORKLOAD_MONTH';
WITH lookup AS (
SELECT MESSMITTEL_UUID,AUFTRAGSNUMMER,MIN(MESSRAUM) AS lab,COUNT(DISTINCT MESSRAUM) AS lab_count
FROM dbo.KALIBRIERUNGEN GROUP BY MESSMITTEL_UUID,AUFTRAGSNUMMER),
times AS (SELECT Artikelnummer,MAX(BearbeitungszeitMin) AS minutes FROM dbo.ArtikelnummerZeit GROUP BY Artikelnummer)
SELECT c.lab,CONVERT(char(7),d.QUITTIERT_AM,126) AS month,COUNT_BIG(*) AS services,
SUM(CASE WHEN t.minutes>0 THEN 1 ELSE 0 END) AS services_with_time,SUM(t.minutes)/60 AS standard_workload_hours
FROM dbo.DIENSTLEISTUNGEN d JOIN lookup c ON d.UUID_KALIBRIERGEGENSTAND=c.MESSMITTEL_UUID AND d.AUFTRAGSNUMMER_SAP=c.AUFTRAGSNUMMER
LEFT JOIN times t ON d.KATALOGNUMMER=t.Artikelnummer
WHERE c.lab_count=1 AND d.QUITTIERT_AM>='2024-01-01' AND d.QUITTIERT_AM<'2026-09-01'
AND d.DIENSTLEISTUNGSTYP IN ('KALIBRIERUNG_WERK','KALIBRIERUNG_DAKKS')
GROUP BY c.lab,CONVERT(char(7),d.QUITTIERT_AM,126) ORDER BY c.lab,month;
PRINT 'ORDER_DATE_COMPLETENESS';
SELECT COUNT_BIG(*) AS positions,COUNT(dateErfasst) AS with_recorded_date,COUNT(dateDlErbracht) AS with_service_date,COUNT(dateAbgeschlossen) AS with_closed_date FROM dbo.AUFTRAGSPOSITIONEN;
